[#187364682] ft-Users should be presented with a reset password link
atlp-rwanda/e-commerce-bitcrafters-fn pull request #17
Opened 2024-06-19 09:47 UTC by Bananayosostene

**What does this PR do?**
This PR introduces the "Forgot Password" functionality to the application. Users who have forgotten their passwords can now request a password reset link by providing their email address. This feature ensures users can regain access to their accounts securely and conveniently. The motivation for adding this feature is to enhance user experience by providing a method to recover account access without administrative intervention.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
The feature has been tested locally by simulating user interactions with the "Forgot Password" and "Reset Password" forms.
Verified that emails are sent successfully and that the reset link works as expected.
Ensured that the new password is correctly updated and allows the user to log in with the new credentials.
Unit tests have been added to cover the new functionality.

Checklist:
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 My changes generate no new warnings
 I have added tests that prove my fix is effective or that my feature works
 New and existing unit tests pass locally with my changes

## What are the relevant pivotal tracker/Trello stories?

## Screenshots (if appropriate)

2024-06-24 00:41 UTC, UwizeyimamaFurahaJustine approved these changes
Good job.

2024-06-24 07:34 UTC, AngeloChristian1 approved these changes

2024-06-24 07:34 UTC, AngeloChristian1 commented on src/test/App.test.tsx
> +
```suggestion
// describe("Should login", () => {
//   it("should render Login ", () => {
//     render(<Login />);
//     const myElement = screen.getByTestId("test-id");
//     expect(myElement).toBeInTheDocument();
//   });
// });

```

2024-06-24 07:34 UTC, AngeloChristian1 commented on src/views/ResetPassword.tsx
> +          <button className="reset-btn text-sm" onClick={handleSubmit}>
You can put the handleSubmit function on the form tag

2024-06-25 17:55 UTC, munezerobagira requested changes

2024-06-25 17:55 UTC, munezerobagira commented on src/views/ForgotPassword.tsx
> +      );
```suggestion
  const axiosClient=useAxiosInstance()
  const handleForgotPassword = async (values: { email: string }) => {
    try {
      const response = await axiosClient.post(
        "/users/reset/link",
        { email: values.email },
      );
```
You can use the instance that @AngeloChristian1 have worked on

2024-06-26 09:03 UTC, Bananayosostene commented on src/views/ForgotPassword.tsx
> +      );
Yes i can use it

2024-06-26 16:50 UTC, munezerobagira approved these changes

2024-06-27 07:07 UTC, merged