Feature: User registration and send email verification
atlp-rwanda/e-commerce-bitcrafters-fn pull request #18
Opened 2024-06-19 09:47 UTC by UwizeyimamaFurahaJustine

## What does this PR do?

Please include a summary of the new feature and the motivation for adding it.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What are the relevant pivotal tracker/Trello stories?

## Screenshots (if appropriate)

2024-06-24 07:24 UTC, EricNiyo73 reviewed
Good work, but you have to make a few improvements
Your deployed link(PR preview) is not working, it seems like you deleted `netlify.toml` file.
Just check on that and the ask again a review.

2024-06-24 07:30 UTC, AngeloChristian1 approved these changes

2024-06-26 05:09 UTC, EricNiyo73 approved these changes

2024-06-26 07:52 UTC, munezerobagira requested changes

2024-06-26 07:52 UTC, munezerobagira commented on src/api/axiosInstance.ts
This have been already worked on by Angelo as hook

2024-06-26 09:37 UTC, munezerobagira approved these changes

2024-06-26 09:37 UTC, merged