[187364689] Users should be able to view and edit their profiles
atlp-rwanda/e-commerce-bitcrafters-fn pull request #22
Opened 2024-06-25 10:03 UTC by Bananayosostene

## What does this PR do?

Please include a summary of the new feature and the motivation for adding it.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What are the relevant pivotal tracker/Trello stories?

## Screenshots (if appropriate)

2024-06-27 16:18 UTC, EricNiyo73 requested changes
1) Why this view profile button is appering here on the login page 
![image](https://github.com/atlp-rwanda/e-commerce-bitcrafters-fn/assets/106761137/ba92e5bb-5534-4b4f-8a9e-41d407989e46)

2) Try to ad the way , if the user is already logged in, can not able to get/view the Login or signup page.

2024-07-01 07:59 UTC, mpanoathos approved these changes

2024-07-01 17:48 UTC, EricNiyo73 approved these changes

2024-07-02 07:31 UTC, munezerobagira approved these changes

2024-07-02 07:32 UTC, merged