[#187364696] Implement notifications pane
atlp-rwanda/e-commerce-bitcrafters-fn pull request #35
Opened 2024-07-05 05:49 UTC by Yvan-David

## What does this PR do?

Please include a summary of the new feature and the motivation for adding it.

1. The notifications pane displays a users notifications
2. The notifications pane should open up when a user clicks on the icon
3. User can see a list of their notifications displayed on the pane

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What are the relevant pivotal tracker/Trello stories?

-  #187364696

## Screenshots (if appropriate)

2024-07-07 18:12 UTC, UwizeyimamaFurahaJustine approved these changes

2024-07-08 07:46 UTC, Bananayosostene approved these changes

2024-07-08 10:00 UTC, munezerobagira requested changes
It would be better if we can this a pop, you can take the insipiration from the chat feature

2024-07-09 08:58 UTC, munezerobagira approved these changes

2024-07-09 08:59 UTC, merged