#[187364670] - Chore(Jest Testing): Adding a testing mechanism with Jest library
atlp-rwanda/e-commerce-bitcrafters-fn pull request #5
Opened 2024-06-12 08:47 UTC by AngeloChristian1

[#Delivers 187364670]

## PR Description: Adding Jest Testing Mechanism

## Summary
This PR introduces Jest testing to our e-commerce website frontend project. The primary motivation behind this change is to enhance code quality and ensure that our application functions correctly across different scenarios.

Testing Approach
I have implemented unit tests using Jest to cover critical components, functions, and user interactions. These tests validate the correctness of our code and help prevent regressions.
To test simply type `npm run test` or `npm t`

Checklist
-  Code adheres to project style guidelines
-  Self-reviewed my changes
-  Added comments to clarify complex sections
-  No new warnings introduced
-  Created tests to verify the effectiveness of my changes
-  Verified that existing unit tests pass locally

Relevant Stories
This PR addresses the following pivotal tracker/Trello story:
[#Delivers 187364670]

## Screenshots (if appropriate)
An example of tests that are running
![Screenshot 2024-06-12 104540](https://github.com/atlp-rwanda/e-commerce-bitcrafters-fn/assets/39400022/fb302319-6260-4b14-b156-feac625ea772)

2024-06-12 13:45 UTC, Yvan-David approved these changes
Great Job

2024-06-13 05:53 UTC, mpanoathos approved these changes

2024-06-13 05:53 UTC, mpanoathos commented on src/test/App.test.tsx
> +  });
Nice

2024-06-13 08:02 UTC, munezerobagira requested changes
Nice work but there few things which can improve

2024-06-13 08:02 UTC, munezerobagira commented on jest.config.cjs
> +    coverageThreshold: {
```suggestion
  collectCoverageFrom: [
     '**/*.{js,jsx}',
     '!**/node_modules/**',
    ],
    coverageThreshold: {
```

2024-06-13 08:02 UTC, munezerobagira commented on jest.config.cjs
> +    coverageThreshold: {
We need to make sure that the coverage is collected from all files

2024-06-13 08:46 UTC, munezerobagira approved these changes

2024-06-13 08:47 UTC, merged