[#187364675] Configure ESLint and Git Precommit hook to run tests
atlp-rwanda/e-commerce-bitcrafters-fn pull request #8
Opened 2024-06-12 18:08 UTC by mpanoathos

## What does this PR do?

Please include a summary of the new feature and the motivation for adding it.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What are the relevant pivotal tracker/Trello stories?

## Screenshots (if appropriate)

2024-06-13 15:34 UTC, munezerobagira requested changes
Good work,
But there just few changes that we can improve

2024-06-13 15:34 UTC, munezerobagira commented on .husky/pre-commit
> +npm test && npm run lint && npm run lint:fix
```suggestion
 npm run lint
```

2024-06-14 06:53 UTC, UwizeyimamaFurahaJustine approved these changes

2024-06-14 07:02 UTC, Yvan-David approved these changes

2024-06-14 07:14 UTC, munezerobagira approved these changes

2024-06-14 07:14 UTC, munezerobagira commented
Nice work

2024-06-14 07:14 UTC, merged