Chore(Storybook): Configuring storybook for component development
atlp-rwanda/e-commerce-bitcrafters-fn pull request #9
Opened 2024-06-12 21:06 UTC by AngeloChristian1

PR Description: Configuring Storybook for Component Isolation

## Summary
This PR introduces Storybook to our React frontend project. Storybook allows us to develop and test components in isolation, making it easier to iterate on UI elements and ensure their correctness.

Type of Change
- [x] New feature (non-breaking change which adds functionality)

### Testing Approach
Since Storybook is primarily a development tool, we don’t need extensive testing within the PR itself. However, we should verify that Storybook runs successfully and that our components render as expected in isolation.
To check for strorybook components run `npm run storybook` and then on localhost visit `port 6006`

Checklist
- [x] Code adheres to project style guidelines
- [x]  Self-reviewed my changes
- [x] Added comments to clarify complex sections
- [x] No new warnings introduced
- [x]  Storybook runs without errors
- [x] (Optional) Created Storybook stories for existing components

### Relevant Stories
This PR addresses the following pivotal tracker
[#Delivers 187364677]

2024-06-13 08:35 UTC, UwizeyimamaFurahaJustine approved these changes
Nice.

2024-06-13 19:41 UTC, Bananayosostene approved these changes

2024-06-14 08:37 UTC, munezerobagira requested changes
remember to add *.stories.tsx and storybook folder in the jest coverage  ignore

2024-06-14 09:24 UTC, munezerobagira approved these changes
Nice work

2024-06-14 09:25 UTC, merged